### ISSUE TITLE
better-queue-memory dependency conflict

### ISSUE THREAD

**Issue by serakfalcon** [diamondio/better-queue-memory#3]
better-queue-memory requires better-queue as a peer dependency.
better-queue requires better-queue-memory as a dependency.
When better-queue is included in a module as a dependency, and that module is used in another project, npm will issue a warning "better-queue-memory requires a peer of better-queue but none is installed. You must install peer dependencies yourself".
This seems to be because better-queue-memory is being detected as a dependency of better-queue, however better-queue does not include itself as a dependency, thus npm thinks it is missing and issues the warning.
Requested resolution:
remove peer dependency of better-queue-memory due to cyclical dependencies. Anyone using better-queue already has better-queue-memory installed. Likewise, if someone wants to use better-queue-memory without better-queue they probably have a reason for it.

**Comment by serakfalcon** [comment]
Steps to replicate:
Include better-queue in a project. Publish that project to npm. Install the project in a new project. run npm install & warning will be issued.

**Comment by leanderlee** [comment]
Thanks for the issue, fixed in 1.0.4
